export const imagePaths: { [key: string]: string[] } = {
  ahri: [
    require("../assets/images/ahri/Ahri_0.jpg"),
    require("../assets/images/ahri/Ahri_1.jpg"),
    require("../assets/images/ahri/Ahri_2.jpg"),
    require("../assets/images/ahri/Ahri_3.jpg"),
    require("../assets/images/ahri/Ahri_4.jpg"),
    require("../assets/images/ahri/Ahri_5.jpg"),
  ],
  garen: [
    require("../assets/images/garen/Garen_0.jpg"),
    require("../assets/images/garen/Garen_1.jpg"),
    require("../assets/images/garen/Garen_2.jpg"),
    require("../assets/images/garen/Garen_3.jpg"),
    require("../assets/images/garen/Garen_4.jpg"),
  ],
  lux: [
    require("../assets/images/lux/Lux_0.jpg"),
    require("../assets/images/lux/Lux_1.jpg"),
    require("../assets/images/lux/Lux_2.jpg"),
    require("../assets/images/lux/Lux_3.jpg"),
    require("../assets/images/lux/Lux_4.jpg"),
    require("../assets/images/lux/Lux_5.jpg"),
  ],
  zed: [
    require("../assets/images/zed/Zed_0.jpg"),
    require("../assets/images/zed/Zed_1.jpg"),
    require("../assets/images/zed/Zed_2.jpg"),
    require("../assets/images/zed/Zed_3.jpg"),
    require("../assets/images/zed/Zed_10.jpg"),
  ],
  jinx: [
    require("../assets/images/jinx/Jinx_0.jpg"),
    require("../assets/images/jinx/Jinx_1.jpg"),
    require("../assets/images/jinx/Jinx_2.jpg"),
    require("../assets/images/jinx/Jinx_3.jpg"),
    require("../assets/images/jinx/Jinx_4.jpg"),
  ],
  thresh: [
    require("../assets/images/thresh/Thresh_0.jpg"),
    require("../assets/images/thresh/Thresh_1.jpg"),
    require("../assets/images/thresh/Thresh_2.jpg"),
    require("../assets/images/thresh/Thresh_3.jpg"),
    require("../assets/images/thresh/Thresh_4.jpg"),
  ],
  katarina: [
    require("../assets/images/katarina/Katarina_0.jpg"),
    require("../assets/images/katarina/Katarina_1.jpg"),
    require("../assets/images/katarina/Katarina_2.jpg"),
    require("../assets/images/katarina/Katarina_3.jpg"),
    require("../assets/images/katarina/Katarina_4.jpg"),
  ],
  leesin: [
    require("../assets/images/leesin/LeeSin_0.jpg"),
    require("../assets/images/leesin/LeeSin_1.jpg"),
    require("../assets/images/leesin/LeeSin_2.jpg"),
    require("../assets/images/leesin/LeeSin_3.jpg"),
    require("../assets/images/leesin/LeeSin_4.jpg"),
  ],
  riven: [
    require("../assets/images/riven/Riven_0.jpg"),
    require("../assets/images/riven/Riven_1.jpg"),
    require("../assets/images/riven/Riven_2.jpg"),
    require("../assets/images/riven/Riven_3.jpg"),
    require("../assets/images/riven/Riven_4.jpg"),
  ],
  vayne: [
    require("../assets/images/vayne/Vayne_0.jpg"),
    require("../assets/images/vayne/Vayne_1.jpg"),
    require("../assets/images/vayne/Vayne_2.jpg"),
    require("../assets/images/vayne/Vayne_3.jpg"),
    require("../assets/images/vayne/Vayne_4.jpg"),
  ],
};
